exp_params:
  to_torch: 1
  to_struct_array: 0
  path_data: "<path_to_input_data>"
  path_target: "<path_to_labels>"
  path_output: "./"
  project_files: ["cgga/cgga_fpkm.csv", "gse154041/gse154041_norm.csv","tcga_gbmlgg/tcga_gbmlgg_fpkm.csv", "cptac_brain/cptac3_fpkm.csv", "glass/glass_tpm.csv" ]  
  projects_tar: ["cgga", "gse154041", "tcga_gbmlgg", "cptac_brain", "glass"] 
  normalization: "log2"
  normalization: "log2"
  data_transformer: "rank"
  feature_selector: "hvg"
  standardizer: "identity"
  algorithm: "DeepSurv"
  evaluation_metric: "c-index"
  n_iter: 60

train_params:
  n_features: [2000, 4000, 6000, 8000, 10000]
  enc_dims: [[512, 256, 128], [256,128,64],[128,64,32],[512,256],[256,128],[128,64],[64,32]]
  surv_dims: [[], [32], [64], [64,32]]
  proj_dims: [64]
  dropout: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7]
  learning_rate: [0.005, 0.001, 0.0005, 0.0001, 0.00005]
  weight_decay: [1.0, 0.5, 0.25, 0.1, 0.05, 0.01]
  batch_size: [256,128,64,32,16]
  epochs: [200, 100, 50, 25, 15, 10, 5, 3]
  n_bins: [5, 10, 15, 20, 25, 30, 50, 100, 200]