exp_params:
  to_torch: 0
  to_struct_array: 1
  path_data: "<path_to_input_data>"
  path_target: "<path_to_labels>"
  path_output: "./"
  project_files: ["cgga/cgga_fpkm.csv", "gse154041/gse154041_norm.csv","tcga_gbmlgg/tcga_gbmlgg_fpkm.csv", "cptac_brain/cptac3_fpkm.csv", "glass/glass_tpm.csv" ]  
  projects_tar: ["cgga", "gse154041", "tcga_gbmlgg", "cptac_brain", "glass"] 
  normalization: "log2"
  data_transformer: "identity"
  feature_selector: "hvg"
  standardizer: "identity"
  algorithm: "GBSA"
  evaluation_metric: "c-index"
  n_iter: 60

train_params:
  learning_rate: [0.001, 0.01, 0.05, 0.1, 0.2]
  n_features: [500, 1000, 5000, 10000]
  n_estimators: [50, 100, 200, 400, 600, 800]
  min_samples_split: [0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  min_samples_leaf: [0.005, 0.01, 0.05, 0.1, 0.15, 0.2]
  max_features: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7]
  max_depth: [3, 5, 7, 9, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
  subsample : [0.6, 0.7, 0.8, 0.9, 1.0]
  n_bins: [5, 10, 15, 20, 25, 30, 50, 100, 200]

